services:
  app:
    build:
      context: ../
      dockerfile: config/Dockerfile
    container_name: chat-app
    working_dir: /app
    env_file:
      - ../app.env
    ports:
      - "11000:11000"
    volumes:
      - deploy_sqlite_dir:/data
    develop:
      watch:
        - path: ../
          action: rebuild
          ignore:
            - ".git"
            - "*.log"
            - "*.env"
            - "data"

volumes:
  deploy_sqlite_dir:
    external: true
