services:
  app:
    build:
      context: ../
      dockerfile: config/Dockerfile
    container_name: simple_chat-app
    working_dir: /app
    env_file:
      - ../app.env
    ports:
      - "11000:11000"
    networks:
      - simple_chat-network
    develop:
      watch:
        - path: ../
          action: rebuild
          ignore:
            - ".git"
            - "*.log"
            - "*.env"
            - "data"

  db:
    image: redis:alpine
    container_name: simple_chat-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - simple_chat-network

networks:
  simple_chat-network:
    driver: bridge
