services:
  app:
    build:
      context: ../
      dockerfile: config/Dockerfile
    container_name: simple_chat
    env_file:
      - ../app.env
    ports:
      - "11000:11000"
    volumes:
      - ../:/app
